name: tradexpro_flutter
description: A new Flutter project for crypto exchange.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.2+3

environment:
  sdk: '>=3.0.0 <4.0.0'
  #flutter: ^3.22.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_localization: ^0.2.0
  cupertino_icons: ^1.0.5
  get: ^4.6.5
  get_storage: ^2.1.1
  intl: ^0.19.0
  connectivity_plus: ^4.0.1
  google_fonts: ^5.0.0
  flutter_svg: ^2.0.7
  fluttertoast: ^8.2.4
  cached_network_image: ^3.2.3
  http: ^1.0.0
  image_picker: ^0.8.9
  image_cropper: ^5.0.0
  url_launcher: ^6.2.2
  webview_flutter: ^4.2.2
  webview_flutter_wkwebview: ^3.5.0
  webview_flutter_android: ^3.8.0
  shared_preferences: ^2.1.2

  auto_size_text: ^3.0.0
  qr_flutter: ^4.1.0
  animated_bottom_navigation_bar: ^1.2.0
  flutter_switch: ^0.3.2
  modal_bottom_sheet: ^2.1.2
  web_socket_channel: ^2.4.0
  intl_phone_number_input: ^0.7.3+1
  country_picker: ^2.0.22
  timeline_tile: ^2.0.0
  share_plus: ^7.0.2
  easy_refresh: ^3.3.2+1
  # crisp: ^0.3.1
  flutter_keyboard_visibility: ^6.0.0
  flutter_stripe: ^10.1.1
  flutter_dotenv: ^5.1.0
  package_info_plus: ^4.0.2
  http_auth: ^1.0.2
  file: ^6.1.4
  textfield_tags: ^2.0.2
  chat_bubbles: ^1.4.1

  flutter_widget_from_html: ^0.14.3
  path_provider: ^2.0.15
  carousel_slider: ^4.2.1
  shimmer: ^3.0.0
  file_picker: ^5.3.4
  flutter_countdown_timer: ^4.1.0
  device_info_plus: ^9.1.1
  firebase_messaging: ^14.7.6
  firebase_core: ^2.24.0
  flutter_local_notifications: ^16.2.0
  local_auth: ^2.1.7
  intercom_flutter: ^8.0.9
  dropdown_search: ^5.0.6
  firebase_crashlytics: ^3.4.9
  firebase_analytics: ^10.8.0
  pin_code_fields: ^8.0.1
  candlesticks: ^2.1.0

dev_dependencies:
#  flutter_test:
#    sdk: flutter
  flutter_lints: ^2.0.1
  change_app_package_name: ^1.1.0  #flutter pub run change_app_package_name:main com.new.package.name

dependency_overrides:
#  http: ^0.13.0
  meta: ^1.10.0

# For information on the generic Dart part of this file, see: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is included with your application.
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - .env
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/CustomIcons.ttf
  # For details regarding fonts see: https://flutter.dev/custom-fonts/#from-packages
