// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoSH6Jmt4Heb7heMGO8cnFJWFmjvUwfCI',
    appId: '1:15813017454:web:c9ceca208e0ccdda168b7f',
    messagingSenderId: '15813017454',
    projectId: 'gittiom-4fc4e',
    authDomain: 'gittiom-4fc4e.firebaseapp.com',
    storageBucket: 'gittiom-4fc4e.appspot.com',
    measurementId: 'G-3L0D9TF3SM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD99_b5Vq9XFiTKpT_LTGRgExihGZ2SShw',
    appId: '1:15813017454:android:5cfd1217299e9fd0168b7f',
    messagingSenderId: '15813017454',
    projectId: 'gittiom-4fc4e',
    storageBucket: 'gittiom-4fc4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLU9GbRd6jQBT2gtr9wGYGp90g5kCSSwg',
    appId: '1:15813017454:ios..:819f0b41ee0619a7168b7f',
    messagingSenderId: '15813017454',
    projectId: 'gittiom-4fc4e',
    storageBucket: 'gittiom-4fc4e.appspot.com',
    iosBundleId: 'com.gittiom.exchange.app',
  );
}
